import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/component/navbar";
import Footer from "@/component/footer";
import { CartProvider } from "@/context/cartContext";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react"; // ✅ Import SessionProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "EatwithMe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SessionProvider> {/* ✅ Wrap Entire App in SessionProvider */}
          <CartProvider>
            <Navbar />
            {children}
            <Footer />
            <Toaster position="top-right" reverseOrder={false} />
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
